matrevy/backstage/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
]

matrevy/common/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

matrevy/revues/urls.py
from django.urls import path

from .views import RevueListView, RevueDetailView


app_name = "revues"

urlpatterns = [
    path("", RevueListView.as_view(), name="index"),
    path("<slug:slug>", RevueDetailView.as_view(), name="detail"),
]

matrevy/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class Account(AbstractUser):
    class Type(models.TextChoices):
        INDIVIDUAL = "INDIVIDUAL", _("Individuel")
        REVUE = "REVUE", _("Revy")

    type = models.CharField(
        _("Type"),
        max_length=30,
        choices=Type.choices,
        default=Type.INDIVIDUAL,
    )
    created = models.DateTimeField(_("oprettet"), auto_now_add=True)
    modified = models.DateTimeField(_("ændret"), auto_now=True)

    class Meta:
        verbose_name = _("konto")
        verbose_name_plural = _("konti")

matrevy/revues/models.py
import os

from django.db import models
from django.utils.translation import gettext_lazy as _

from django_hosts.resolvers import reverse


def upload_poster_path(instance, filename):
    _, ext = os.path.splitext(filename)
    filename = instance.slug + ext
    return f"revues/posters/{filename}"


class Revue(models.Model):
    """
    TODO
    """

    slug = models.SlugField(_("URL-slug"), unique=True)
    title = models.CharField(_("titel"), max_length=200)
    description = models.TextField(_("beskrivelse"), blank=True)
    opening_date = models.DateField(_("premierdato"))
    # closing_date = models.DateField(_("slutdato"))
    poster = models.ImageField(
        _("plakat"),
        upload_to=upload_poster_path,
        blank=True,
    )

    objects = models.Manager()

    class Meta:
        verbose_name = _("revy")
        verbose_name_plural = _("revyer")
        ordering = ["-opening_date"]
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        kwargs = {
            "slug": self.slug,
        }
        return reverse("revues:detail", host="matrevy", kwargs=kwargs)

    @property
    def year(self):
        return self.opening_date.year


class Scene(models.Model):
    """
    Model for scenes
    """

    class SceneType(models.TextChoices):
        SKETCH = "SKETCH", _("Sketch")
        SONG = "SONG", _("Song")
        VIDEO = "VIDEO", _("Video")
        # DANCE = "DANCE", _("Dans")
        # INTERLUDE = "INTERLUDE", _("Pausefisk")
        # MEDLEY = "MEDLEY", _("Medley")

    title = models.CharField(_("titel"), max_length=200)
    type = models.CharField(_("type"), max_length=20, choices=SceneType.choices, default=SceneType.SKETCH)
    duration = models.IntegerField(_("varighed"), blank=True, null=True)
    # author = models.CharField(_("forfatter"), max_length=100)
    revue = models.ForeignKey(Revue, on_delete=models.CASCADE)
    act_no = models.PositiveIntegerField()
    scene_no = models.PositiveIntegerField()

    class Meta:
        verbose_name = _("scene")
        verbose_name_plural = _("scener")
        ordering = ["-revue", "act_no", "scene_no"]

    def __str__(self):
        return self.title

matrevy/backstage/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "backstage/index.html"

matrevy/common/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

matrevy/revues/views.py
from django.views.generic import DetailView, ListView

from .models import Revue


class RevueListView(ListView):
    model = Revue
    context_object_name = "revues"
    template_name = "revues/revues_list.html"


class RevueDetailView(DetailView):
    model = Revue
    context_object_name = "revue"
    template_name = "revues/revue_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            next_revue = self.object.get_next_by_opening_date()
        except Revue.DoesNotExist:
            next_revue = None

        try:
            prev_revue = self.object.get_previous_by_opening_date()
        except Revue.DoesNotExist:
            prev_revue = None

        context.update({
            "next": next_revue,
            "prev": prev_revue,
        })
        return context

templates/backstage/index.html
<!DOCTYPE html>
<html lang="da">
  <head>
    <title>Backstage</title>
  </head>

  <body>
    Hello, world!
  </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="da">
  <head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Favicons -->
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
  </head>

  <body>

    {% include 'includes/header.html' %}

    <!-- BEGIN content -->
    <main>
      <div class="container my-3">
        {% block content %}{% endblock %}
      </div>
    </main>
    <!-- END content -->

    {% include 'includes/footer.html' %}

    <!-- JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Matematikrevy{% endblock %}

{% block content %}
<h1>Matematikrevy</h1>
{% endblock %}

templates/includes/footer.html
<!-- BEGIN footer -->
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3 mb-3 mb-lg-0">
        <h3 class="footer__heading">Kontakt</h3>
        <address>
          Matematikrevy<br>
          Universitetsparken 5<br>
          DK-2100 København Ø<br>
          CVR: 37985406
        </address>
      </div>

      <div class="col-md-3 mb-3 mb-lg-0">
        <h3 class="footer__heading">Matematikrevy</h3>
        <ul class="list-unstyled">
          <li>
            <a class="footer__link" href="#">Om revyen</a>
          </li>
          <li>
            <a class="footer__link" href="#">Vær med</a>
          </li>
          <li>
            <a class="footer__link" href="#">Presse</a>
          </li>
          <li>
            <a class="footer__link" href="#">Spørgsmål og svar</a>
          </li>
          <li>
            <a class="footer__link" href="#">Kontakt</a>
          </li>
        </ul>
      </div>

      <div class="col-md-3 mb-3 mb-lg-0">
        <h3 class="footer__heading">Andre revyer</h3>
        <ul class="list-unstyled">
          <li>
            <a class="footer__link" href="http://www.biorevy.dk" target="_blank" rel="external nofollow">BIOREVY</a>
          </li>
          <li>
            <a class="footer__link" href="http://www.dikurevy.dk" target="_blank" rel="external nofollow">DIKUrevy</a>
          </li>
          <li>
            <a class="footer__link" href="http://www.facebook.com/fysikrevy" target="_blank" rel="external nofollow">FysikRevy&trade;</a>
          </li>
          <li>
            <a class="footer__link" href="http://www.facebook.com/KemiRevy-243693629547944" target="_blank" rel="external nofollow">KemiRevy</a>
          </li>
          <li>
            <a class="footer__link" href="http://www.facebook.com/MBKrevyen" target="_blank" rel="external nofollow">MBK Revy</a>
          </li>
        </ul>
      </div>

      <div class="col-md-3 mb-3 mb-lg-0">
        <h3 class="footer__heading">Sociale medier</h3>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a class="btn btn-social" href="http://www.facebook.com/matrevy"><span class="fa fa-facebook-f"></span></a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-social"  href="http://www.youtube.com/user/Matematikrevyen"><span class="fa fa-youtube-play"></span></a>
          </li>
          <li class="list-inline-item">
            <a class="btn btn-social"  href="http://www.snapchat.com/add/matrevy"><span class="fa fa-snapchat-ghost"></span></a>
          </li>
        </ul>
      </div>
    </div>

    <hr class="footer__divider">

    <div class="row">
      <div class="col-md-6 text-center text-md-left">
        &copy; {% now "Y" %} Matematikrevy. Alle rettigheder forbeholdes.
      </div>

      <div class="col-md-6 text-center text-md-right">
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <a class="footer__link footer__link--legal" href="#">Vilkår</a>
          </li>
          <li class="list-inline-item">
            <a class="footer__link footer__link--legal" href="#">Persondata</a>
          </li>
          <li class="list-inline-item">
            <a class="footer__link footer__link--legal" href="#">Cookies</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- END footer -->

templates/includes/header.html
{% load static %}

<!-- BEGIN header -->
<header class="site-header">
  <nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static 'img/matrevy-logo.svg' %}" width="212" height="40" alt="Matematikrevy">
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="fa fa-bars"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Om revyen</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Billetter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'revues:index' %}">Tidligere år</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sponsorer</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Kontakt</a>
          </li>
        </ul>
        <a class="btn btn-outline-light" href="#"><span class="fa fa-sign-in"></span> Log ind</a>
      </div>
    </div>
  </nav>
</header>
<!-- END header -->

templates/revues/revue_detail.html
{% extends 'base.html' %}

{% block title %}{{ revue.title }} | Matematikrevy{% endblock %}

{% block content %}
  <h2>{{ revue.title }}</h2>

  {% with scenes=revue.scene_set.all %}
  <h3>Aktoversigt</h3>
  {% regroup scenes by act_no as acts %}
  <ul>
  {% for act in acts %}
      <li>Akt {{ act.grouper }}
      <ul>
      {% for scene in act.list %}
        <li>{{ scene.title }}</li>
      {% endfor %}
      </ul>
      </li>
  {% endfor %}
  {% endwith %}
  </ul>
  {% if prev %}
  <li class="prev">
    <a rel="prev" href="{{ prev.get_absolute_url }}">Forrige</a>
  </li>
  {% endif %}
  {% if next %}
  <li class="next">
    <a rel="next" href="{{ next.get_absolute_url }}">Næste</a>
  </li>
  {% endif %}
{% endblock %}

templates/revues/revue_list.html
{% extends 'base.html' %}

{% block title %}Tidligere år | Matematikrevy{% endblock %}

{% block content %}
  <h2>Tidligere revyer</h2>
  Test
  <ul>
  {% for revue in revues %}
    <li><a href={{ revue.get_absolute_url }}>{{ revue.title }}</a></li>
  {% endfor %}
  </ul>
{% endblock %}